# Generated by Django 4.0.2 on 2022-02-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Completed')], default=None, max_length=2, null=True),
        ),
    ]
