# Generated by Django 4.0.2 on 2022-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasklists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("CP", "Complete"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
    ]
