# Generated by Django 4.0.2 on 2022-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasklists", "0002_task_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
