# Generated by Django 4.0.2 on 2022-03-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasklists", "0003_alter_task_state"),
        ("tasklists", "0003_task_notes"),
    ]

    operations = []
