# Generated by Django 4.0.2 on 2022-03-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasklists", "0005_tasklist_task_tasklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tasklist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasklists.tasklist",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="list_name",
            field=models.CharField(max_length=20),
        ),
    ]
