<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-26 17:20
=======
# Generated by Django 4.0.2 on 2022-03-27 00:18
>>>>>>> fa74508ab2e49328f0c4430368477cccccd77c59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('tasklists', '0005_tasklist_task_tasklist'),
=======
        ("tasklists", "0005_tasklist_task_tasklist"),
>>>>>>> fa74508ab2e49328f0c4430368477cccccd77c59
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasklists.tasklist'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='list_name',
=======
            model_name="task",
            name="tasklist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasklists.tasklist",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="list_name",
>>>>>>> fa74508ab2e49328f0c4430368477cccccd77c59
            field=models.CharField(max_length=20),
        ),
    ]
