# Generated by Django 4.0.2 on 2022-03-29 05:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasklists", "0007_alter_tasklist_list_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tasklist",
            unique_together={("owner", "list_name")},
        ),
    ]
